name: basic-install
on: [push,workflow_dispatch]
jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v4
      - name: dependencies
        run: npm ci
      - name: lint-code
        run: npm run lint
  build-code:
    needs: lint-code
    runs-on: ubuntu-latest
    steps:
      - name: building-code
        run: npm run build
  deploy-code:
    needs: build-code
    runs-on: ubuntu-latest
    steps:
      - name: deploying-code
        run: npm run deploy

  
